"""
Diffusion-generated image loader.

Loads synthetic face images generated by diffusion models for cross-generator
evaluation. Supports loading from CSV manifests or from raw directories.
"""

import os
from pathlib import Path
from typing import Optional, Tuple, List

import cv2
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2


SUPPORTED_GENERATORS = [
    "stable_diffusion_v1_5",
    "stable_diffusion_v2_1",
    "midjourney",
    "dall_e_3",
]


class DiffusionFaceDataset(Dataset):
    """Dataset for diffusion-generated face images paired with real faces."""

    def __init__(
        self,
        real_dir: str = "",
        fake_dir: str = "",
        generator: str = "stable_diffusion_v1_5",
        transform: Optional[A.Compose] = None,
        max_samples: Optional[int] = None,
        csv_path: Optional[str] = None,
    ):
        """
        Args:
            real_dir: Directory containing real face images (directory mode).
            fake_dir: Directory containing diffusion-generated face images (directory mode).
            generator: Name of the generator (for metadata tracking).
            transform: Albumentations transform pipeline.
            max_samples: Maximum number of samples per class (directory mode only).
            csv_path: Path to a CSV manifest. If provided, ignores directory-based loading.
        """
        self.real_dir = Path(real_dir) if real_dir else None
        self.fake_dir = Path(fake_dir) if fake_dir else None
        self.generator = generator
        self.transform = transform or self._default_transform()
        self.csv_path = csv_path

        if csv_path:
            self.samples = self._load_from_csv(csv_path)
        else:
            self.samples = self._collect_samples(max_samples)

    def _default_transform(self) -> A.Compose:
        return A.Compose([
            A.Resize(128, 128),
            A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ToTensorV2(),
        ])

    def _load_from_csv(self, csv_path: str) -> List[Tuple[str, int]]:
        """Load samples from a CSV manifest file."""
        df = pd.read_csv(csv_path)
        samples = [(row["path"], int(row["label"])) for _, row in df.iterrows()]
        return samples

    def _collect_samples(self, max_samples: Optional[int]) -> List[Tuple[str, int]]:
        """Collect image paths and labels from real/fake directories."""
        image_extensions = {".png", ".jpg", ".jpeg", ".bmp", ".tiff"}

        real_images = sorted([
            p for p in self.real_dir.iterdir()
            if p.suffix.lower() in image_extensions
        ]) if self.real_dir and self.real_dir.exists() else []

        fake_images = sorted([
            p for p in self.fake_dir.iterdir()
            if p.suffix.lower() in image_extensions
        ]) if self.fake_dir and self.fake_dir.exists() else []

        if max_samples is not None:
            real_images = real_images[:max_samples]
            fake_images = fake_images[:max_samples]

        samples = [(str(p), 0) for p in real_images]
        samples += [(str(p), 1) for p in fake_images]

        return samples

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        img_path, label = self.samples[idx]
        image = cv2.imread(img_path)
        if image is None:
            raise FileNotFoundError(f"Could not read image: {img_path}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        transformed = self.transform(image=image)
        image = transformed["image"]

        return image, label


def get_diffusion_dataloader(
    real_dir: str = "",
    fake_dir: str = "",
    generator: str = "stable_diffusion_v1_5",
    batch_size: int = 32,
    num_workers: int = 4,
    transform: Optional[A.Compose] = None,
    max_samples: Optional[int] = None,
    csv_path: Optional[str] = None,
) -> DataLoader:
    """
    Create a DataLoader for diffusion-generated vs. real images.

    Can load from a CSV manifest (preferred) or from raw directories.
    """
    dataset = DiffusionFaceDataset(
        real_dir=real_dir,
        fake_dir=fake_dir,
        generator=generator,
        transform=transform,
        max_samples=max_samples,
        csv_path=csv_path,
    )
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
    )
